budget_taged:
    path:     /
    defaults: { _controller: "OCBudgeBundle:Budget_taged:index" }

budget_taged_show:
    path:     /{id}/show
    defaults: { _controller: "OCBudgeBundle:Budget_taged:show" }

budget_taged_new:
    path:     /new
    defaults: { _controller: "OCBudgeBundle:Budget_taged:new" }

budget_taged_create:
    path:     /create
    defaults: { _controller: "OCBudgeBundle:Budget_taged:create" }
    methods:  POST

budget_taged_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCBudgeBundle:Budget_taged:edit" }

budget_taged_update:
    path:     /{id}/update
    defaults: { _controller: "OCBudgeBundle:Budget_taged:update" }
    methods:  [POST, PUT]

budget_taged_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCBudgeBundle:Budget_taged:delete" }
    methods:  [POST, DELETE]
