classe:
    path:     /
    defaults: { _controller: "OCBudgeBundle:Classe:index" }

classe_show:
    path:     /{id}/show
    defaults: { _controller: "OCBudgeBundle:Classe:show" }

classe_new:
    path:     /new
    defaults: { _controller: "OCBudgeBundle:Classe:new" }

classe_create:
    path:     /create
    defaults: { _controller: "OCBudgeBundle:Classe:create" }
    methods:  POST

classe_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCBudgeBundle:Classe:edit" }

classe_update:
    path:     /{id}/update
    defaults: { _controller: "OCBudgeBundle:Classe:update" }
    methods:  [POST, PUT]

classe_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCBudgeBundle:Classe:delete" }
    methods:  [POST, DELETE]
