contrat:
    path:     /
    defaults: { _controller: "OCBudgeBundle:Contrat:index" }

contrat_show:
    path:     /{id}/show
    defaults: { _controller: "OCBudgeBundle:Contrat:show" }

contrat_new:
    path:     /new
    defaults: { _controller: "OCBudgeBundle:Contrat:new" }

contrat_create:
    path:     /create
    defaults: { _controller: "OCBudgeBundle:Contrat:create" }
    methods:  POST

contrat_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCBudgeBundle:Contrat:edit" }

contrat_update:
    path:     /{id}/update
    defaults: { _controller: "OCBudgeBundle:Contrat:update" }
    methods:  [POST, PUT]

contrat_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCBudgeBundle:Contrat:delete" }
    methods:  [POST, DELETE]
