groupement:
    path:     /
    defaults: { _controller: "OCBudgeBundle:Groupement:index" }

groupement_show:
    path:     /{id}/show
    defaults: { _controller: "OCBudgeBundle:Groupement:show" }

groupement_new:
    path:     /new
    defaults: { _controller: "OCBudgeBundle:Groupement:new" }

groupement_create:
    path:     /create
    defaults: { _controller: "OCBudgeBundle:Groupement:create" }
    methods:  POST

groupement_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCBudgeBundle:Groupement:edit" }

groupement_update:
    path:     /{id}/update
    defaults: { _controller: "OCBudgeBundle:Groupement:update" }
    methods:  [POST, PUT]

groupement_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCBudgeBundle:Groupement:delete" }
    methods:  [POST, DELETE]
