ministere:
    path:     /
    defaults: { _controller: "OCBudgeBundle:Ministere:index" }

ministere_show:
    path:     /{id}/show
    defaults: { _controller: "OCBudgeBundle:Ministere:show" }

ministere_new:
    path:     /new
    defaults: { _controller: "OCBudgeBundle:Ministere:new" }

ministere_create:
    path:     /create
    defaults: { _controller: "OCBudgeBundle:Ministere:create" }
    methods:  POST

ministere_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCBudgeBundle:Ministere:edit" }

ministere_update:
    path:     /{id}/update
    defaults: { _controller: "OCBudgeBundle:Ministere:update" }
    methods:  [POST, PUT]

ministere_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCBudgeBundle:Ministere:delete" }
    methods:  [POST, DELETE]
