ordonnancement:
    path:     /
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:index" }

ordonnancement_show:
    path:     /{id}/show
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:show" }

ordonnancement_new:
    path:     /new
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:new" }

ordonnancement_create:
    path:     /create
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:create" }
    methods:  POST

ordonnancement_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:edit" }

ordonnancement_update:
    path:     /{id}/update
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:update" }
    methods:  [POST, PUT]

ordonnancement_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCBudgeBundle:Ordonnancement:delete" }
    methods:  [POST, DELETE]
