oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /

oc_budge:
    resource: "@OCBudgeBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
