oc_user_homepage:
    path:     /hello
    defaults: { _controller: OCUserBundle:Default:index }

fos_user_security_login:
    path: /login
    defaults: { _controller: OCUserBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: OCUserBundle:Security:check }
    methods : [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: OCUserBundle:Security:logout }


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_registration_register:
    path: /
    defaults: { _controller: OCUserBundle:Registration:register }
    methods : [GET POST]
fos_user_registration_check_email:
    path: /check-email
    defaults: { _controller: OCUserBundle:Registration:checkEmail }
fos_user_registration_confirm:
    path: /confirm
    defaults: { _controller: OCUserBundle:Registration:confirm }
fos_user_registration_confirmed:
     path: /confirmed
     defaults: { _controller: OCUserBundle:Registration:confirmed }
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile