<?php

namespace OC\Bundle\BudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Appel_offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Appel_offreRepository extends EntityRepository
{
}
