<?php

namespace OC\Bundle\BudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Budget_tagedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Budget_tagedRepository extends EntityRepository
{
}
