<?php

namespace OC\Bundle\BudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Line_BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Line_BudgetRepository extends EntityRepository
{
}
