<?php

namespace OC\Bundle\BudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MinistereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinistereRepository extends EntityRepository
{
}
