<?php

namespace OC\Bundle\BudgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdonnancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdonnancementRepository extends EntityRepository
{
}
