oc_budge_line_budget:
    resource: "@OCBudgeBundle/Resources/config/routing/line_budget.yml"
    prefix:   /line_budget

oc_budge_homepage:
    path:     /hello/{name}
    defaults: { _controller: OCBudgeBundle:Default:index }
oc_budge_home:
    path:     /
    defaults: { _controller: OCBudgeBundle:Default:home }
oc_budge_dashbord:
    path:     /dashbord
    defaults: { _controller: OCBudgeBundle:Dashbord:dashbord }    