## YAML Template.
fos_user_registration_register:
    path: /
    defaults: { _controller: OCUserBundle:Registration:register }
    methods : [GET]
fos_user_registration_check_email:
    path: /check-email
    defaults: { _controller: OCUserBundle:Registration:checkEmail }
fos_user_registration_confirm:
    path: /confirm
    defaults: { _controller: OCUserBundle:Registration:confirm }
fos_user_registration_confirmed:
    path: /confirmed
    defaults: { _controller: OCUserBundle:Registration:confirmed }
