Activity:
    type: entity
    table: activity
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        credit:
            type: integer
            nullable: false
            options:
                unsigned: false
        outressource:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prix:
            type: integer
            nullable: false
            options:
                unsigned: false
        source:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nature:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        typerealisation:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
