AppelOffre:
    type: entity
    table: appel_offre
    indexes:
        IDX_BC56FD47AD745416:
            columns:
                - ministere_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        labelAppelOffre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: label_appel_offre
        dateLimiteDeposer:
            type: datetime
            nullable: false
            column: date_limite_deposer
    manyToOne:
        ministere:
            targetEntity: Ministere
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ministere_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
