Budget:
    type: entity
    table: budget
    indexes:
        IDX_73F2F77B86A85DCA:
            columns:
                - line_budget_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        year:
            type: integer
            nullable: false
            options:
                unsigned: false
        credite:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: creditE
        creditp:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: creditP
        creditce:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: creditCE
        creditcp:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: creditCP
    manyToOne:
        lineBudget:
            targetEntity: LineBudget
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                line_budget_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
