Classe:
    type: entity
    table: classe
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        labelClass:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: label_class
        articleclasse:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: articleClasse
    lifecycleCallbacks: {  }
