Consommation:
    type: entity
    table: consommation
    indexes:
        IDX_F993F0A286A85DCA:
            columns:
                - line_budget_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        year:
            type: integer
            nullable: false
            options:
                unsigned: false
        ordonnanceEngagement:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: ordonnance_engagement
        ordonnancePayement:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: ordonnance_payement
        dateLecture:
            type: datetime
            nullable: false
            column: date_lecture
    manyToOne:
        lineBudget:
            targetEntity: LineBudget
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                line_budget_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
