Groupement:
    type: entity
    table: groupement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        labelGroupement:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: label_groupement
    manyToMany:
        lineBudget:
            targetEntity: LineBudget
            cascade: {  }
            fetch: LAZY
            mappedBy: groupement
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
