LineBudget:
    type: entity
    table: line_budget
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        article:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        parag:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        sParag:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: s_parag
        region:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
        labelLine:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: label_line
        ministere:
            type: integer
            nullable: false
            options:
                unsigned: false
        programeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: programe_id
    manyToMany:
        groupement:
            targetEntity: Groupement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: lineBudget
            joinTable:
                name: linegroupement
                joinColumns:
                    -
                        name: line_budget_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: groupement_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
