Mouvement:
    type: entity
    table: mouvement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeMouvement:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: type_mouvement
        dateMouvement:
            type: datetime
            nullable: false
            column: date_mouvement
        montant:
            type: integer
            nullable: false
            options:
                unsigned: false
        lof:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: LoF
    lifecycleCallbacks: {  }
