Ordonnancement:
    type: entity
    table: ordonnancement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        year:
            type: integer
            nullable: false
            options:
                unsigned: false
        pay:
            type: float
            nullable: false
            precision: 10
            scale: 0
        date:
            type: datetime
            nullable: false
        cout:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
