Programe:
    type: entity
    table: programe
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        labelprog:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: labelProg
        code:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        head:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
    lifecycleCallbacks: {  }
