TypeContrat:
    type: entity
    table: type_contrat
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descTypeContrat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: desc_type_contrat
    lifecycleCallbacks: {  }
